sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: ZbACX3+5YDDMTv9qL3iYQf8koUo/+sDk9vSnOTE+NzQBOsgDjTXBWrHa6PNrw/mK0tdFENUjVCVyNVewj0Z6cHqeooOdlxFmVjlcwsQzxsin9C7mvyc5nxZb57FVNgy7Li1yguxu+Iq75l/2juJNaLTvYvUfwi6HxCvtTNcRz4jeYgbsckuFFYZOdyn7YA1VUFxqlPS3iUfpb2jqKAdTwONMa2D29MeDCJTVJAEpp8TCumnfNCZcTuVYI0zGafzlPauAtL9wCcjolWj8qqiSx2RT80w1LCkvn5TIAy7vugBvcKgAOvYXDqbc36+RS04ThltgC0OsdFCG7m/baU0oHFezL0OY3rB2Pvsbm2dMJZIGZRse1GLbuUV/JXeBMQec+irQ+fDyCIz0u3dxOg3bxtHYymyUMilXiqWRPF9JmXH+n/iWrU9YzEWx6h8pMnJ3vnDo3ih/rGkVgacX7p3eXGmxdDiPNM8leD/WIjTmUxAKfEF2zg5sXWp3OjGLZdfer1y3FWXLtZFziGr69Yu3y1vQafdEQSNU6wA0MkkgRY9fNhl6XwTvXtoDaDV/9xeKspUZxdIT+Nk78mNJXAX9othvzw+Ekxia0wZW10Au66/pPSg+Ore1nHG5nuyR/lgGNWawn7qlQnCT2xNH3v5D9ygbqHR4nzRsnDQjSVDJzdQ=
branches:
  only:
  - master
